name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    # run every Wednesday
    - cron: '31 23 * * 2'
  push:
    branches:
       - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: peterstadler/existdb


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - IMAGE_TAG: |
                6
                6.0
                6.0.1
                latest
            EXIST_VERSION: "6.0.1"
            EXIST_URL: https://github.com/eXist-db/exist/releases/download/eXist-6.0.1/exist-installer-6.0.1.jar
            SAXON_JAR: /opt/exist/lib/Saxon-HE-9.9.1-8.jar
          - IMAGE_TAG: |
                5
                5.5
                5.5.0
            EXIST_VERSION: "5.5.0"
            EXIST_URL: https://github.com/eXist-db/exist/releases/download/eXist-5.5.0/exist-installer-5.5.0.jar
            SAXON_JAR: /opt/exist/lib/Saxon-HE-9.9.1-8.jar
          - IMAGE_TAG: |
                5.4
                5.4.1
            EXIST_VERSION: "5.4.1"
            EXIST_URL: https://github.com/eXist-db/exist/releases/download/eXist-5.4.1/exist-installer-5.4.1.jar
            SAXON_JAR: /opt/exist/lib/Saxon-HE-9.9.1-8.jar
          - IMAGE_TAG: |
                4
                4.10
                4.10.0
            EXIST_VERSION: "4.10.0"
            EXIST_URL: https://github.com/eXist-db/exist/releases/download/eXist-4.10.0/eXist-db-setup-4.10.0.jar
            SAXON_JAR: /opt/exist/lib/endorsed/Saxon-HE-9.6.0-7.jar 
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PETERS_GITHUB_TOKEN }}
      
      # Login against DockerHub registry except on PR
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PETERS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PETERS_DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ secrets.PETERS_DOCKERHUB_USERNAME }}/existdb
          tags: ${{ matrix.IMAGE_TAG }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
         context: .
         build-args: |
           VERSION=${{ matrix.EXIST_VERSION }}
           EXIST_URL=${{ matrix.EXIST_URL }}
           SAXON_JAR=${{ matrix.SAXON_JAR }}
         push: ${{ github.event_name != 'pull_request' }}
         platforms: |
            linux/amd64
            linux/arm64/v8
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
